kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: gitrepo2
spec:
  repo: https://github.com/manno/fleet-experiments
  branch: main
  paths:
    - multiple-paths/service
  targets:
    - clusterSelector: {}
